version: '3.8'

services:
  web:
    image: betserver
    build:
      context: .
    ports:
      - "80:8080"
    command: ["sh", "-c", "chmod +x /app/start.sh && /app/start.sh"]
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ev_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

volumes:
  postgres_data:
