version: '3.8'

services:
  web:
    image: betserver
    build:
      context: .
    ports:
      - "80:8080"
    command: ["sh", "-c", "chmod +x /app/start.sh && /app/start.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
