# Generated by Django 5.0.2 on 2024-02-26 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField()),
                ('first_odd_id', models.IntegerField()),
                ('second_odd_id', models.IntegerField()),
                ('sport_id', models.IntegerField()),
                ('sport_name', models.CharField(max_length=20)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Sportsbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('selected', models.BooleanField(default=False)),
                ('tenis_url', models.CharField(max_length=50)),
                ('darts_url', models.CharField(max_length=50)),
                ('cricket_url', models.CharField(max_length=50)),
                ('baseball_url', models.CharField(max_length=50)),
                ('table_tennis_url', models.CharField(max_length=50)),
                ('snooker_url', models.CharField(max_length=50)),
                ('volleyball_url', models.CharField(max_length=50)),
                ('football_url', models.CharField(max_length=50)),
                ('hockey_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='url',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='ArbitrageBetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('sportsbook_name', models.CharField(max_length=10)),
                ('opportunity_name', models.CharField(max_length=50)),
                ('odd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('arbitrage_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='database.arbitragebet')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=50)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sport')),
                ('sportsbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sportsbook')),
            ],
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_event_links', to='database.event')),
                ('second_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_event_links', to='database.event')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opp_description', models.CharField(max_length=50)),
                ('tip_type', models.CharField(max_length=3)),
                ('opp_number', models.CharField(max_length=10)),
                ('market_id', models.CharField(max_length=10)),
                ('bet_order', models.IntegerField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sport')),
                ('sportsbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sportsbook')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_opportunity_links', to='database.opportunity')),
                ('second_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_opportunity_links', to='database.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Odd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_id', models.IntegerField()),
                ('tip_type', models.CharField(max_length=3)),
                ('odd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='database.event')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.opportunity')),
                ('sportsbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sportsbook')),
            ],
        ),
        migrations.CreateModel(
            name='EventToBeLinked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_id', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.event')),
                ('sportsbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sportsbook')),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='sport_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.sporttype'),
        ),
    ]
