# Generated by Django 5.0.2 on 2024-02-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_arbitragebet_sportsbook_sporttype_sport_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opp_description',
            field=models.CharField(max_length=200),
        ),
    ]
