# Generated by Django 5.0.2 on 2024-02-26 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_opportunity_opp_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragebetdetail',
            name='player_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sporttype'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='url',
            field=models.CharField(max_length=20),
        ),
    ]
