# Generated by Django 5.0.2 on 2024-02-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_arbitragebetdetail_player_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['sportsbook_id', 'sport_id', 'tip_type', 'opp_number', 'market_id', 'bet_order'], name='database_op_sportsb_a5e560_idx'),
        ),
    ]
