# Generated by Django 5.0.2 on 2024-02-29 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_opportunity_database_op_sportsb_a5e560_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OddLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OddToBeLinked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tried_to_link', models.BooleanField(default=False)),
                ('sport_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='eventlink',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='eventtobelinked',
            name='tried_to_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='eventtobelinked',
            index=models.Index(fields=['sport_id'], name='database_ev_sport_i_9538a1_idx'),
        ),
        migrations.AddField(
            model_name='oddlink',
            name='first_odd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_odd_links', to='database.odd'),
        ),
        migrations.AddField(
            model_name='oddlink',
            name='second_odd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_odd_links', to='database.odd'),
        ),
        migrations.AddField(
            model_name='oddtobelinked',
            name='odd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.odd'),
        ),
        migrations.AddIndex(
            model_name='oddtobelinked',
            index=models.Index(fields=['sport_id'], name='database_od_sport_i_ed2fd8_idx'),
        ),
    ]
