# Generated by Django 5.0.2 on 2024-02-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_oddlink_oddtobelinked_eventlink_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbitragebetdetail',
            old_name='amount',
            new_name='ammount',
        ),
    ]
