# Generated by Django 5.0.2 on 2024-03-02 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_rename_amount_arbitragebetdetail_ammount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtobelinked',
            name='tried_to_link',
        ),
        migrations.RemoveField(
            model_name='oddtobelinked',
            name='tried_to_link',
        ),
        migrations.AddField(
            model_name='eventlink',
            name='sport_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='oddlink',
            name='opportunity_link',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.opportunitylink'),
        ),
        migrations.AddField(
            model_name='oddlink',
            name='sport_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='oddtobelinked',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='oddstobelinked', to='database.event'),
        ),
        migrations.AddField(
            model_name='oddtobelinked',
            name='opportunity_link',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.opportunitylink'),
        ),
    ]
