# Generated by Django 5.0.2 on 2024-04-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_eventtobelinked_tried_to_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragebet',
            name='updated',
            field=models.CharField(max_length=30),
        ),
    ]
