# Generated by Django 5.0.2 on 2024-04-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_arbitragebet_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragebet',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
