# Generated by Django 5.0.2 on 2024-04-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_arbitragebet_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbitragebetdetail',
            old_name='ammount',
            new_name='amount',
        ),
    ]
