# Generated by Django 5.0.2 on 2024-04-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_rename_ammount_arbitragebetdetail_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragebet',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='arbitragebetdetail',
            name='sportsbook_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sportsbook',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
