# Generated by Django 5.0.2 on 2024-04-28 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_arbitragebet_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddlink',
            name='first_odd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_odd_links', to='database.odd'),
        ),
        migrations.AlterField(
            model_name='oddlink',
            name='second_odd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_odd_links', to='database.odd'),
        ),
    ]
