# Generated by Django 5.0.2 on 2024-04-28 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_oddlink_first_odd_alter_oddlink_second_odd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odd',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='odds', to='database.event'),
        ),
    ]
