# Generated by Django 5.0.2 on 2024-05-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_odd_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityToBeLinked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.opportunity')),
                ('target_sportsbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities_to_be_linked', to='database.sportsbook')),
            ],
        ),
    ]
