# Generated by Django 5.0.2 on 2024-05-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_opportunitytobelinked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragebetdetail',
            name='opportunity_name',
            field=models.CharField(max_length=200),
        ),
    ]
