# Generated by Django 5.0.2 on 2024-05-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_arbitragebetdetail_opportunity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragebet',
            name='profit',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='arbitragebetdetail',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
