# Generated by Django 5.0.2 on 2024-06-09 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_arbitragebet_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddtobelinked',
            name='odd',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='oddstobelinked', to='database.odd'),
        ),
    ]
