# Generated by Django 5.0.2 on 2024-06-20 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_oddtobelinked_odd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oddtobelinked',
            name='event',
        ),
        migrations.RemoveField(
            model_name='oddtobelinked',
            name='odd',
        ),
        migrations.RemoveField(
            model_name='oddtobelinked',
            name='opportunity_link',
        ),
        migrations.RemoveField(
            model_name='opportunitylink',
            name='first_opportunity',
        ),
        migrations.RemoveField(
            model_name='opportunitylink',
            name='second_opportunity',
        ),
        migrations.RemoveField(
            model_name='oddlink',
            name='opportunity_link',
        ),
        migrations.RemoveField(
            model_name='opportunitytobelinked',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='opportunitytobelinked',
            name='target_sportsbook',
        ),
        migrations.AlterField(
            model_name='odd',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='database.event'),
        ),
        migrations.AlterField(
            model_name='oddlink',
            name='first_odd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_odd_links', to='database.odd'),
        ),
        migrations.AlterField(
            model_name='oddlink',
            name='second_odd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_odd_links', to='database.odd'),
        ),
        migrations.CreateModel(
            name='ParentOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('linked_opportunity', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_to', to='database.parentopportunity')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sport')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='database.parentopportunity'),
        ),
        migrations.DeleteModel(
            name='EventToBeLinked',
        ),
        migrations.DeleteModel(
            name='OddToBeLinked',
        ),
        migrations.DeleteModel(
            name='OpportunityLink',
        ),
        migrations.DeleteModel(
            name='OpportunityToBeLinked',
        ),
    ]
