# Generated by Django 5.0.6 on 2024-07-10 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_remove_oddtobelinked_event_remove_oddtobelinked_odd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitragebetdetail',
            name='arbitrage_bet',
        ),
        migrations.RemoveField(
            model_name='eventlink',
            name='first_event',
        ),
        migrations.RemoveField(
            model_name='eventlink',
            name='second_event',
        ),
        migrations.RemoveField(
            model_name='oddlink',
            name='first_odd',
        ),
        migrations.RemoveField(
            model_name='oddlink',
            name='second_odd',
        ),
        migrations.RemoveField(
            model_name='parentopportunity',
            name='linked_opportunity',
        ),
        migrations.RemoveField(
            model_name='parentopportunity',
            name='sport',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='database.opportunity'),
        ),
        migrations.RemoveField(
            model_name='sport',
            name='sport_type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='second_name',
            new_name='away',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='first_name',
            new_name='home',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='database.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='odd',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='odd',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='database.odd'),
        ),
        migrations.AddField(
            model_name='odd',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportsbook',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ArbitrageBet',
        ),
        migrations.DeleteModel(
            name='ArbitrageBetDetail',
        ),
        migrations.DeleteModel(
            name='EventLink',
        ),
        migrations.DeleteModel(
            name='OddLink',
        ),
        migrations.DeleteModel(
            name='ParentOpportunity',
        ),
        migrations.DeleteModel(
            name='SportType',
        ),
    ]
