# Generated by Django 5.0.6 on 2024-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_remove_arbitragebetdetail_arbitrage_bet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
