# Generated by Django 5.0.6 on 2024-07-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
