# Generated by Django 5.0.6 on 2024-07-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
