# Generated by Django 5.0.6 on 2024-07-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_alter_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odd',
            old_name='bet_id',
            new_name='odd_id',
        ),
        migrations.RemoveField(
            model_name='odd',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='odd',
            name='tip_type',
        ),
    ]
