# Generated by Django 5.0.6 on 2024-07-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_rename_bet_id_odd_odd_id_remove_odd_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odd',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odd',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
