# Generated by Django 5.0.6 on 2024-07-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_odd_code_odd_locked'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='opportunity',
            name='database_op_sportsb_a5e560_idx',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='opp_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='bet_order',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='market_id',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='opp_number',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='tip_type',
        ),
        migrations.AddField(
            model_name='odd',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['sportsbook_id', 'sport_id'], name='database_op_sportsb_2ca163_idx'),
        ),
    ]
