# Generated by Django 5.0.6 on 2024-07-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_remove_opportunity_database_op_sportsb_a5e560_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='market_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
