# Generated by Django 5.0.6 on 2024-07-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_opportunity_market_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='odd',
            name='movement',
            field=models.IntegerField(default=0),
        ),
    ]
