# Generated by Django 5.0.6 on 2024-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_odd_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='prefered',
            field=models.BooleanField(default=False),
        ),
    ]
