# Generated by Django 5.0.6 on 2024-07-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_opportunity_prefered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsbook',
            name='baseball_url',
        ),
        migrations.RemoveField(
            model_name='sportsbook',
            name='cricket_url',
        ),
        migrations.RemoveField(
            model_name='sportsbook',
            name='darts_url',
        ),
        migrations.RemoveField(
            model_name='sportsbook',
            name='snooker_url',
        ),
        migrations.AddField(
            model_name='sportsbook',
            name='basketball_url',
            field=models.CharField(default='f', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsbook',
            name='box_url',
            field=models.CharField(default='f', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsbook',
            name='handball_url',
            field=models.CharField(default='f', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sportsbook',
            name='football_url',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sportsbook',
            name='hockey_url',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sportsbook',
            name='table_tennis_url',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sportsbook',
            name='tenis_url',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sportsbook',
            name='volleyball_url',
            field=models.CharField(max_length=20),
        ),
    ]
