# Generated by Django 5.0.6 on 2024-08-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_remove_sportsbook_baseball_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=60),
        ),
    ]
