# Generated by Django 5.0.6 on 2024-08-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_alter_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsbookMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('sportsbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='database.sportsbook')),
            ],
        ),
    ]
