# Generated by Django 5.0.6 on 2024-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_sportsbookmarket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odd',
            name='odd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
