# Generated by Django 5.0.6 on 2024-08-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_alter_odd_odd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odd',
            name='odd_id',
            field=models.BigIntegerField(),
        ),
    ]
