# Generated by Django 5.0.6 on 2024-08-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_alter_odd_odd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='odd',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
