# Generated by Django 5.0.6 on 2024-08-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_odd_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odd',
            name='position',
        ),
    ]
