# Generated by Django 5.1 on 2024-09-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_event_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='used',
        ),
        migrations.AddField(
            model_name='odd',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
