# Generated by Django 5.1 on 2024-09-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0039_remove_event_used_odd_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odd',
            name='odd',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
