# Generated by Django 5.1 on 2024-09-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0040_alter_odd_odd'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='league_id',
            field=models.IntegerField(default=0),
        ),
    ]
