# Generated by Django 5.1 on 2024-10-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0041_event_league_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odd',
            name='used',
        ),
        migrations.AddField(
            model_name='event',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
