# Generated by Django 5.1 on 2025-01-09 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_remove_odd_used_event_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='league_id',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='market_id',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='url',
        ),
        migrations.RemoveField(
            model_name='sportsbook',
            name='basketball_url',
        ),
        migrations.RemoveField(
            model_name='sportsbook',
            name='box_url',
        ),
        migrations.RemoveField(
            model_name='sportsbook',
            name='football_url',
        ),
        migrations.RemoveField(
            model_name='sportsbook',
            name='handball_url',
        ),
        migrations.RemoveField(
            model_name='sportsbook',
            name='hockey_url',
        ),
        migrations.RemoveField(
            model_name='sportsbook',
            name='table_tennis_url',
        ),
        migrations.RemoveField(
            model_name='sportsbook',
            name='tenis_url',
        ),
        migrations.RemoveField(
            model_name='sportsbook',
            name='volleyball_url',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_id', models.BigIntegerField()),
                ('movement', models.IntegerField(default=0)),
                ('odds', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='database.event')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.opportunity')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='database.price')),
                ('sportsbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sportsbook')),
            ],
        ),
        migrations.DeleteModel(
            name='Odd',
        ),
    ]
