"""Add_arbitrage_details

Revision ID: 2801526b8852
Revises: c0cc921bdb26
Create Date: 2024-02-17 20:55:19.433189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2801526b8852'
down_revision = 'c0cc921bdb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arbitragebetdetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arbitragebet_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=30), nullable=False),
    sa.Column('sportsbook_name', sa.String(length=10), nullable=False),
    sa.Column('opportunity_name', sa.String(length=50), nullable=False),
    sa.Column('odd', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('ammount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['arbitragebet_id'], ['arbitragebet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arbitragebet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('sport_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('profit', sa.Numeric(precision=6, scale=2), nullable=False))
        batch_op.drop_column('implied_prob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arbitragebet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('implied_prob', sa.NUMERIC(precision=6, scale=2), nullable=False))
        batch_op.drop_column('profit')
        batch_op.drop_column('sport_name')
        batch_op.drop_column('updated')

    op.drop_table('arbitragebetdetail')
    # ### end Alembic commands ###
