"""Add_odd_tip

Revision ID: 983a064cf00c
Revises: 9d25fb782481
Create Date: 2024-02-18 20:06:03.180746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983a064cf00c'
down_revision = '9d25fb782481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odd', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tip_type', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odd', schema=None) as batch_op:
        batch_op.drop_column('tip_type')

    # ### end Alembic commands ###
