"""Add_sport_url

Revision ID: 9d25fb782481
Revises: b9cd01091885
Create Date: 2024-02-18 11:34:37.036642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d25fb782481'
down_revision = 'b9cd01091885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
