"""Add_sports_selected

Revision ID: b9cd01091885
Revises: 2801526b8852
Create Date: 2024-02-18 01:56:02.991091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cd01091885'
down_revision = '2801526b8852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected', sa.Boolean(), nullable=True))

    with op.batch_alter_table('sportsbook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sportsbook', schema=None) as batch_op:
        batch_op.drop_column('selected')

    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.drop_column('selected')

    # ### end Alembic commands ###
