"""add_arbitrage_bets

Revision ID: c0cc921bdb26
Revises: f777b0c3eb2c
Create Date: 2024-02-16 17:57:01.581376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0cc921bdb26'
down_revision = 'f777b0c3eb2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arbitragebet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('implied_prob', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('first_odd_id', sa.Integer(), nullable=False),
    sa.Column('second_odd_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arbitragebet')
    # ### end Alembic commands ###
