"""initial migration

Revision ID: f777b0c3eb2c
Revises: 
Create Date: 2024-02-16 02:10:12.088270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f777b0c3eb2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sportsbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tenis_url', sa.String(length=50), nullable=False),
    sa.Column('darts_url', sa.String(length=50), nullable=False),
    sa.Column('cricket_url', sa.String(length=50), nullable=False),
    sa.Column('baseball_url', sa.String(length=50), nullable=False),
    sa.Column('table_tennis_url', sa.String(length=50), nullable=False),
    sa.Column('snooker_url', sa.String(length=50), nullable=False),
    sa.Column('volleyball_url', sa.String(length=50), nullable=False),
    sa.Column('football_url', sa.String(length=50), nullable=False),
    sa.Column('hockey_url', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sporttype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('sport_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_type_id'], ['sporttype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('second_name', sa.String(length=50), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sportsbook_id', sa.Integer(), nullable=False),
    sa.Column('opp_description', sa.String(length=50), nullable=False),
    sa.Column('tip_type', sa.String(length=3), nullable=True),
    sa.Column('opp_number', sa.String(length=10), nullable=True),
    sa.Column('market_id', sa.String(length=10), nullable=True),
    sa.Column('bet_order', sa.Integer(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sport.id'], ),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_event_id', sa.Integer(), nullable=False),
    sa.Column('second_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventtobelinked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('odd', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['event.sportsbook_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunitylink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_opportunity_id', sa.Integer(), nullable=False),
    sa.Column('second_opportunity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['second_opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunitylink')
    op.drop_table('odd')
    op.drop_table('eventtobelinked')
    op.drop_table('eventlink')
    op.drop_table('opportunity')
    op.drop_table('event')
    op.drop_table('sport')
    op.drop_table('sporttype')
    op.drop_table('sportsbook')
    # ### end Alembic commands ###
